<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Smoke" duration-ms="721" started-at="2020-03-15T03:05:58 IST" finished-at="2020-03-15T03:05:58 IST">
    <groups>
    </groups>
    <test name="Smoke" duration-ms="721" started-at="2020-03-15T03:05:58 IST" finished-at="2020-03-15T03:05:58 IST">
      <class name="com.project.Testcases.NavigateAndLoginToSauceDemo">
        <test-method status="PASS" signature="onStart()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@69379752]" name="onStart" is-config="true" duration-ms="753" started-at="2020-03-15T03:05:57 IST" finished-at="2020-03-15T03:05:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onStart -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@69379752]" name="beforeTest" is-config="true" duration-ms="1" started-at="2020-03-15T03:05:58 IST" finished-at="2020-03-15T03:05:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="pageObjects()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@69379752]" name="pageObjects" is-config="true" duration-ms="33" started-at="2020-03-15T03:05:58 IST" finished-at="2020-03-15T03:05:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pageObjects -->
        <test-method status="FAIL" signature="navigateToSauceDemo(java.lang.String, java.lang.String)[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@69379752]" name="navigateToSauceDemo" duration-ms="57" started-at="2020-03-15T03:05:58 IST" description="Navigate to the given test site and asserting it&#039;s title" finished-at="2020-03-15T03:05:58 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[saucedemo]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.project.Utility.MethodLibrary.waitForPageToLoad(MethodLibrary.java:351)
at com.project.Testcases.NavigateAndLoginToSauceDemo.navigateToSauceDemo(NavigateAndLoginToSauceDemo.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToSauceDemo -->
        <test-method status="SKIP" signature="loginToSauceDemo(java.lang.String, java.lang.String)[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@69379752]" name="loginToSauceDemo" duration-ms="0" started-at="2020-03-15T03:05:58 IST" description="Logging in to given test site and asserting it&#039;s title" depends-on-methods="com.project.Testcases.NavigateAndLoginToSauceDemo.navigateToSauceDemo" finished-at="2020-03-15T03:05:58 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NavigateAndLoginToSauceDemo.loginToSauceDemo(java.lang.String, java.lang.String)[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@69379752] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NavigateAndLoginToSauceDemo.loginToSauceDemo(java.lang.String, java.lang.String)[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@69379752] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:99)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSauceDemo -->
        <test-method status="SKIP" signature="logoutOfSauceDemo()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@69379752]" name="logoutOfSauceDemo" duration-ms="0" started-at="2020-03-15T03:05:58 IST" description="Logging out of given test site and asserting it&#039;s title" depends-on-methods="com.project.Testcases.NavigateAndLoginToSauceDemo.loginToSauceDemo" finished-at="2020-03-15T03:05:58 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method NavigateAndLoginToSauceDemo.logoutOfSauceDemo()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@69379752] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method NavigateAndLoginToSauceDemo.logoutOfSauceDemo()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@69379752] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:99)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOfSauceDemo -->
        <test-method status="PASS" signature="finishedTest()[pri:0, instance:com.project.Testcases.NavigateAndLoginToSauceDemo@69379752]" name="finishedTest" is-config="true" duration-ms="1" started-at="2020-03-15T03:05:58 IST" finished-at="2020-03-15T03:05:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finishedTest -->
      </class> <!-- com.project.Testcases.NavigateAndLoginToSauceDemo -->
    </test> <!-- Smoke -->
  </suite> <!-- Smoke -->
</testng-results>
